/**
 * @license
 * Copyright 2025-2026 Open Home Foundation
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * connectedhomeip's sample MEI cluster XML, the format referenced by
 * https://github.com/matter-js/matterjs-server/issues/324. Inlined (rather than read from a fixture
 * file on disk) so it survives the package's compile-then-run test pipeline unchanged.
 *
 * Source: https://github.com/project-chip/connectedhomeip/blob/master/src/app/zap-templates/zcl/data-model/chip/sample-mei-cluster.xml
 */
export const SAMPLE_MEI_CLUSTER_XML = `<?xml version="1.0"?>
<configurator>
  <domain name="CHIP"/>
  <cluster>
    <domain>General</domain>
    <name>Sample MEI</name>
    <code>0xFFF1FC20</code>
    <define>SAMPLE_MEI_CLUSTER</define>
    <description>The Sample MEI cluster showcases a cluster manufacturer extensions</description>

    <attribute side="server" code="0x0000" define="FLIP_FLOP" type="boolean" writable="true" default="false" optional="false">FlipFlop</attribute>

    <command source="server" code="0x01" name="AddArgumentsResponse" optional="false" disableDefaultResponse="true">
      <description>Response for AddArguments that returns the sum.</description>
      <arg name="returnValue" type="int8u"/>
    </command>

    <command source="client" code="0x02" name="AddArguments" response="AddArgumentsResponse" optional="false">
      <description>Command that takes two uint8 arguments and returns their sum.</description>
      <arg name="arg1" type="int8u"/>
      <arg name="arg2" type="int8u"/>
    </command>

    <command source="client" code="0x00" name="Ping" optional="false">
      <description>Simple command without any parameters and without a response.</description>
    </command>

    <event side="server" code="0x0000" name="PingCountEvent" priority="info" isFabricSensitive="true" optional="false">
      <description>Example events generated by Ping command</description>
      <field id="1" name="count" type="int32u"/>
    </event>
  </cluster>
</configurator>
`;

/**
 * A real-world custom cluster shipped in Silicon Labs' sample apps, used here as an independent
 * cross-check: its type mapping (SINGLE/INT32U, uppercase) and attribute IDs were verified against the
 * sample's generated C++ accessors (AccessorsExtension.h) during development of the generator.
 *
 * Source: https://github.com/SiliconLabsSoftware/matter_applications/blob/master/matter_thread_sparkfun_weather_station_mad/matter_weather_station_extension.xml
 */
export const WEATHER_STATION_CLUSTER_XML = `<?xml version="1.0"?>
<configurator>
    <domain name="CHIP" />
    <cluster>
        <domain>Measurement &amp; Sensing</domain>
        <name>Weather Station</name>
        <code>0xFFF1FEDC</code>
        <define>WEATHER_STATION_CLUSTER</define>
        <description>The Sample cluster showcases a weather station Matter device</description>

        <attribute side="server" code="0x0000" define="WIND_SPEED" type="SINGLE" writable="true"
            default="0" optional="false">Wind Speed</attribute>
        <attribute side="server" code="0x0001" define="WIND_DIRECTION" type="INT32U" writable="true"
            default="0" optional="false">Wind Direction</attribute>
        <attribute side="server" code="0x0002" define="RAINFALL" type="SINGLE" writable="true"
            default="0" optional="false">Rainfall</attribute>
    </cluster>
</configurator>
`;
